### ISSUE TITLE
Use...

### ISSUE THREAD

**Issue by gregorskii** [djm/remark-shortcodes#13]
May be a slightly dumb question, but how do you actually use the shortcode nodes to create HTML in your tree. What happens AFTER ```use(shortcodes, {startBlock: "[[", endBlock: "]]", inlineMode: true})``` to make them convert to html/react/whatever?

This may be a unified plugin misunderstanding, but my custom parser is not working. It runs, but the tree is never given to it.

```
const attacher = (options) => {
  console.log('HELLO', options);

  return (tree, file) => {
    console.log(tree);

    visit(tree, 'shortcodes', (node) => {
      console.log(node);
    });
  };
};
```

Thanks

**Comment by gregorskii** [comment]
For anyone else looking its a transformer not a parser or compiler:

```
const shortcodeTransformer = () => {
  return (tree, file, next) => {
    visit(tree, 'shortcode', function(node) {
      //console.log(node);
      let type = node.identifier;
      let attrs = node.attributes;
      let content = transformContent(type, attrs);

      node.type = 'html';
      node.value = content;

      next();
    });
  }
};
```

**Comment by gregorskii** [comment]
Also to save a bunch of time... use `process` not `processSync` when creating your nodes with the above transformer.

**Comment by akemrir** [comment]
I have tested this, transformer works well it transorms, but prepare objects are not rendered.
@gregorskii Could you show more complete example?

@gregorskii Is it possible to return react component in transformContent?

**Comment by gregorskii** [comment]
I’ve tried a ton to return a react component directly. I wasn’t able to. It’s passing the raw HTML from the content to rebuke-react. And that lib does not pass through already created react components.

IMO this lib would be so much more useful if it could parse the args from the shortcode as props to custom components rather than going through HTML first.

Did the example above work? It was a complete set of code.

**Comment by akemrir** [comment]
Nope. I`ve managed to use this on some way, but without resoulting html.
https://codesandbox.io/s/infallible-pike-bfj9y

@gregorskii  Could you take, a look?
From where you have schema and raw?

**Comment by smarajitdasgupta** [comment]
@gregorskii @akemrir were you able to render shortcode as html?

**Comment by gregorskii** [comment]
I was only able to do what I listed above. That example is almost exactly what I ended up using instead production. I had to render it to html first then convert it to React as I described.
