### ISSUE TITLE
Minified React error #418 when using remark-shortcodes in React application

### ISSUE THREAD

**Issue by dineshr5** [djm/remark-shortcodes#29]
I am encountering a "Minified React error #418" when using the remark-shortcodes package in my React application. This error appears when rendering articles that include markdown processed by the remark-shortcodes package. The error message suggests a problem with how React components are being used or imported, and it points to a compatibility issue with remark-shortcodes.

Expected Behavior:
Markdown content with shortcodes should be rendered correctly without causing any React errors.

Actual Behavior:
The application throws a "Minified React error #418" in the console, and the markdown content does not render as expected.

Additional Information:

- The last update to remark-shortcodes was five years ago, and it may not be compatible with the latest versions of React.

Error Details:

`Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
`

**Comment by djm** [comment]
This package is long dead @dineshr5, I'd recommend a different one (see README).

**Comment by dineshr5** [comment]
@djm I have used 'remark-directive' as mentioned in README but the scenarios thats comes under "{{ }}" open and closed blocks is not supported by remark-directives. any thoughts?
<img width="427" alt="Screenshot 2024-08-07 at 7 17 14 PM" src="https://github.com/user-attachments/assets/2c0b89d9-cd2e-482c-ac43-b8401218f44d">

**Comment by djm** [comment]
Sorry, I’m not familiar with the other package - you’re best off asking them! Thanks.
