### ISSUE TITLE
Enclosing shortcodes, feature suggestion.

### ISSUE THREAD

**Issue by daveybrown** [djm/remark-shortcodes#7]
Is there any plan for enclosing shortcodes? Something like this?

[WordPress - Enclosing Shortcodes docs](https://developer.wordpress.org/plugins/shortcodes/enclosing-shortcodes/)

**Comment by daveybrown** [comment]
I have built a solution for this, it's a little rough around the edges but please let me know if you'd like a look and I'll create a fork and pull request.

**Comment by olivierkastel** [comment]
@daveybrown Can you share what you did to solve the problem ?

**Comment by daveybrown** [comment]
Hi mate, check my 2 recent commits here : https://github.com/daveybrown/remark-shortcodes/commits/enclosing-shortcodes

They should give you something that works, but hasn't been extensively tested. In the end I went with a different solution all together and I'm not using remark on my project, so my recolection of the work is a bit hazy.

It should be self explanatory but give me a shout if you hit a brick wall with it.

Cheers,
Davey
