### ISSUE TITLE
Release version 0.3.0 to NPM

### ISSUE THREAD

**Issue by fusionfox** [djm/remark-shortcodes#8]
Hello 👋 

The package version has been bumped to 0.3.0 but this hasn't been released to NPM. Would it be possible to get this released? 

There are some new features that seem to have been added in 0.3.0 that we need 👍

**Comment by RikJurriaans** [comment]
bumb

**Comment by djm** [comment]
I'm aware of this - I refuse to waste more time with Travis though; it's
turned into a smoking junk heap since the redundancies.

Once Github Actions is enabled on my account, I'll link this up to npm.

I might do a manual one in the meantime - I'll see if I get time this
weekend.

**Comment by RikJurriaans** [comment]
Cool, that would be awesome. Thanks for your time.

**Comment by davakh** [comment]
Hi, how it's going with 0.3.0 version?

**Comment by jay-airtable** [comment]
Open source is hard, thank you for you work 🥇  Please upload the new version for us if you have some time.

**Comment by djm** [comment]
Many moons after they were written: v0.3.0 and v0.3.1 are out, and actually on `npm` this time. Sorry about the delay, life got in the way.

v0.3.1 updates a few dependencies to remove the some (non-severe) vulnerabilities in the deps. 

cc/ @yuliyan @j-dowell @fusionfox @jay-airtable @davakh @RikJurriaans 

Special thanks for the reminder @jay-airtable.
